=== pmd/pmd/pmd-test-schema/src/main/resources/net/sourceforge/pmd/test/schema/rule-tests_1_0_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://pmd.sourceforge.net/rule-tests"
        targetNamespace="http://pmd.sourceforge.net/rule-tests"
        elementFormDefault="qualified">

    <element name="test-data">
        <complexType>
            <choice maxOccurs="unbounded">
                <element name="test-code" minOccurs="0" maxOccurs="unbounded" type="tns:testType"/>
                <element name="code-fragment" minOccurs="0" maxOccurs="unbounded" type="tns:codeFragmentType">
                    <annotation>
                        <documentation>
                            A code fragment that can be referred to by several tests.
                        </documentation>
                    </annotation>
                </element>
            </choice>
        </complexType>
    </element>

    <complexType name="testType">
        <sequence>
            <element name="description" type="string"/>
            <element name="rule-property" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <simpleContent>
                        <extension base="string">
                            <attribute name="name" type="string" use="required"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>

            <element name="expected-problems" type="nonNegativeInteger"/>
            <element name="expected-linenumbers" type="string" minOccurs="0"/>
            <element name="expected-messages" minOccurs="0">
                <complexType>
                    <sequence>
                        <element name="message" type="string" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
            <choice>
                <element name="code" type="string"/>
                <element name="code-ref">
                    <complexType>
                        <attribute name="id" type="IDREF" use="required"/>
                    </complexType>
                </element>
            </choice>
            <element name="source-type" minOccurs="0" default="" type="string">
                <annotation>
                    <documentation>
                        Language version of the source, eg 'java 8'.
                    </documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="reinitializeRule" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="regressionTest" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated. Use "disabled" instead.
                    If this attribute is set to "false", then the test is ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="useAuxClasspath" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>

        <attribute name="disabled" type="boolean" default="false">
            <annotation>
                <documentation>
                    A reason why the test is disabled/ignored should be provided as a comment for the test.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="focused" type="boolean" default="false">
            <annotation>
                <documentation>
                    If true, only this test will be executed, and all others will be disabled.
                    If several tests in the same file are focused, then the last one wins, in
                    document order.
                    This attribute is provided as a way for developers to temporarily focus on a single test.
                    Test files with a focused test should not be checked in. For this reason,
                    using this attribute produces a warning.
                </documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="codeFragmentType">
        <simpleContent>
            <extension base="string">
                <attribute name="id" type="ID" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/naming/xml/SuspiciousHashcodeMethodName.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">
    <test-code>
        <description><![CDATA[
ok
     ]]></description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
 public int hashCode() {return 42;}
}
     ]]></code>
    </test-code>
    <test-code>
        <description><![CDATA[
hashcode
     ]]></description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
 public int hashcode() {return 42;}
}
     ]]></code>
    </test-code>
    <test-code>
        <description><![CDATA[
HashCode
     ]]></description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
 public int HashCode() {return 42;}
}
     ]]></code>
    </test-code>
    <test-code>
        <description><![CDATA[
Hashcode
     ]]></description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
 public int Hashcode() {return 42;}
}
     ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/xml/NcssTypeCount.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>short</description>
        <rule-property name="minimum">13</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void foo() {
        bar();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>lots of comments</description>
        <rule-property name="minimum">13</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void foo() {
        //nothing to see here
        //nothing to see here
        //nothing to see here
        //nothing to see here
        bar();
        //nothing to see here
        //nothing to see here
        //nothing to see here
        //nothing to see here
        foo();
    }
}
        ]]></code>
    </test-code>

    <code-fragment id="long-method"><![CDATA[
public class Foo {
    public void foo() {
        //nothing to see here
        //nothing to see here
        //nothing to see here
        //nothing to see here
        bar();
        bar();
        bar();
        bar();
        bar();
        bar();
        //nothing to see here
        //nothing to see here
        //nothing to see here
        //nothing to see here
        foo();
        foo();
        foo();
        foo();
        foo();
        foo();
    }
}
    ]]></code-fragment>

    <test-code>
        <description>long method</description>
        <rule-property name="minimum">13</rule-property>
        <expected-problems>1</expected-problems>
        <code-ref id="long-method"/>
    </test-code>

    <test-code>
        <description>long method - changed minimum</description>
        <!-- validated this number against NCSS -->
        <rule-property name="minimum">15</rule-property>
        <expected-problems>0</expected-problems>
        <code-ref id="long-method"/>
    </test-code>

    <test-code>
        <description>Github issue #251 - lines are counted properly</description>
        <rule-property name="minimum">10</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
@isTest
private class AcceptanceTests_Test {

    @isTest
    private static void test() {
        // Setup
        Opportunity o1 = new Opportunity()
                                    .add(new Contact().foo(1)  .bar(1).year(2012)  .bar(1).price(5)  .vol(100))
                                    .add(new Contact().foo(1)  .bar(2).year(2013)  .bar(1).price(5)  .vol(110))
                                    .add(new Contact().foo(1)  .bar(3).year(2014)  .bar(1).price(5)  .vol(120))
                                    .add(new Contact().foo(1)  .bar(4).year(2015)  .bar(1).price(5)  .vol(130))
                                    .persist();

        // Verify
        System.assert(attribute());
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1396 Method with comment</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
/**
 * Class comment
 */
public class SomeClass {
    /**
     * Comment
     */
    public void doSomething() {
        System.debug('hello world');
    }

    /** Field comment */
    private String field;
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidCatchingNPE.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>failure case</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>4</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (NullPointerException e) {
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>catching another type, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (FooException e) {
        }
    }
    public static class FooException extends NullPointerException {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>throwing it, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        throw new NullPointerException();
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseStringBufferLength.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Using length properly</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        StringBuffer sb = new StringBuffer();
        if ( sb.length() == 0 ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
    void bar2() {
        StringBuilder sb = new StringBuilder();
        if ( sb.length() == 0 ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <!-- Note: this changed in PMD 7. -->
        <description>StringBuffer.toString.equals(""), bad</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        StringBuffer sb = new StringBuffer();
        if ( sb.toString().equals("") ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
    void bar2() {
        StringBuilder sb = new StringBuilder();
        if ( sb.toString().equals("") ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>StringBuffer.toString.equals("foo"), ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        StringBuffer sb = new StringBuffer();
        if ( sb.toString().equals("foo") ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
    void bar2() {
        StringBuilder sb = new StringBuilder();
        if ( sb.toString().equals("foo") ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>StringBuffer.toString.length(), bad</description>
        <expected-problems>2</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        StringBuffer sb = new StringBuffer();
        if ( sb.toString().length() == 0 ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
    void bar2() {
        StringBuilder sb = new StringBuilder();
        if ( sb.toString().length() == 0 ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>no literals</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    boolean bar(Object foo) {
        StringBuffer sb = new StringBuffer();
        return sb.toString().equals(foo);
    }
    boolean bar2(Object foo) {
        StringBuilder sb = new StringBuilder();
        return sb.toString().equals(foo);
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>empty + non-empty string sb.toString().equals("" + "x"), ok (as in: do not use StringBuffer.length())</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    boolean bar() {
        StringBuffer sb = new StringBuffer();
        return sb.toString().equals("" + "x");
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>sb.toString().trim().equals(""), ok (as in: do not use StringBuffer.length())</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    boolean bar() {
        StringBuffer sb = new StringBuffer(" ");
        return sb.toString().trim().equals("");
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>sb.toString().equals(baz("")), ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    boolean bar() {
        StringBuffer sb = new StringBuffer();
        return sb.toString().equals(baz(""));
    }
    String baz(String s) {
        return s + "x";
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>sb.toString().trim().length == 0, ok (as in: do not use StringBuffer.length())</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    boolean bar() {
        StringBuffer sb = new StringBuffer();
        return sb.toString().trim().length == 0;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1177 Incorrect StringBuffer warning when that class is not used</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Ineffecient
{
    public static String getValue(int in)
    {
        Integer i = new Integer(in);
        if (i.toString().length() == 1)
        {
            return "length 1";
        }
        return "";
    }

    public String toString()
    {
        return "Ineffecient";
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>[java] UseStringBufferLength: false negative with empty string variable #3639</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>5</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    public void foo() {
        StringBuffer sb = new StringBuffer("any_string");
        final String nullStr = "";
        if (sb.toString().equals(nullStr)) { // PMD should report a warning here
            System.out.println("Buffer is empty");
        }

        // the preferred way
        if (sb.length() == 0) {
            System.out.println("Buffer is empty");
        }
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/rule/performance/xml/AvoidConsoleStatements.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
        xmlns="http://pmd.sourceforge.net/rule-tests"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests https://pmd.github.io/schema/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Any console method should be flagged</description>
        <expected-problems>9</expected-problems>
        <code><![CDATA[
console.log('foo');
console.error('foo');
console.info('foo');
console.warn('foo');
console.debug('foo');
console.trace('foo');
console.assert(false, 'foo');
console.dir(myObj);
console.group('label');
]]></code>
    </test-code>

    <test-code>
        <description>Any console method via window.console should be flagged</description>
        <expected-problems>9</expected-problems>
        <code><![CDATA[
window.console.log('foo');
window.console.error('foo');
window.console.info('foo');
window.console.warn('foo');
window.console.debug('foo');
window.console.trace('foo');
window.console.assert(false, 'foo');
window.console.dir(myObj);
window.console.group('label');
]]></code>
    </test-code>

    <test-code>
        <description>Other similar methods shouldn't be flagged</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
var MyFoo = {
    debug: function(a) {
        // ...
    },
    console: {
        debug: function(a) {
            // ...
        }
    }
};

MyFoo.debug('bar'); // ok, it is not console.debug
MyFoo.console.debug('bar'); // ok, it is not console.debug
]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryLocalBeforeReturn.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>skip void/native/abstract methods</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {}
    public native int buz();
    public abstract int baz();
}
        ]]></code>
    </test-code>

    <test-code>
        <description>skip literal returns</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() { return 5; }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>simple failure case</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int x = doSomething();
        return x;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>skip complicated returns</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int x = doSomething();
        return x == null ? foo : bar;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>skip method calls</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        return doSomething(a, b, c);
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1495 [java] UnnecessaryLocalBeforeReturn with assert</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int res = 2; assert res>=0;
        return res;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#219 ClassCastException in switch case with local variable returned</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public int m(int val) {
        switch (vl) {
            default:
                int i = 0;
                return i;
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Detect violation even if not on consecutive lines</description>
        <rule-property name="statementOrderMatters">false</rule-property>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int res = 2;
        doSomething();
        return res;
    }

    public void doSomething() { }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>No violations on multiple uses of the variable</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int res = 2;
        doSomething(res);
        return res;
    }

    public void doSomething(int x) { }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>No violations on multiple uses of the variable - statement order does not matter</description>
        <rule-property name="statementOrderMatters">false</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int res = 2;
        doSomething(res);
        return res;
    }

    public void doSomething(int x) { }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#933 UnnecessaryLocalBeforeReturn false positive for SuppressWarnings annotation</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class TestCase<T> {
    T getSomeT() { return null; }
    private static <T> T findEventTypeValueByName(TestCase<?> unchecked) {
        @SuppressWarnings("unchecked")
        T result = (T) unchecked.getSomeT();
        return result;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#282 UnnecessaryLocalBeforeReturn false positive when cloning Maps</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.util.concurrent.ConcurrentHashMap;
import java.util.Map;
import java.util.HashMap;
public class CustomerErrorCollector {

    private final ConcurrentHashMap<String, String> customerErrors = new ConcurrentHashMap<>();

    public void error(String customerNr, String errorMsg) {
        customerErrors.put(customerNr, errorMsg);
    }

    public Map<String, String> getAndReset() {
        final Map<String, String> copy = new HashMap<>(customerErrors);
        customerErrors.clear();
        return copy; // PMD complains that variable could be avoided
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#310 UnnecessaryLocalBeforeReturn enhancement is overly restrictive -- method order matters</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Mutable {
    public int example1() {
        int i = compute(); // might throw
        markComputationDone();
        return i; // PMD complains that variable could be avoided
    }

    public int example2() {
        Mutable m = new Mutable();
        int i = compute(m);
        sideEffect(m);
        return i;
    }
    static void sideEffect(Mutable m) {}
    static int sideEffect(Mutable m) {}
    static int compute() {}
    static int markComputationDone() {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#310 UnnecessaryLocalBeforeReturn statement order does not matter</description>
        <rule-property name="statementOrderMatters">false</rule-property>
        <expected-problems>2</expected-problems>
        <expected-linenumbers>3,10</expected-linenumbers>
        <code><![CDATA[
public class Mutable {
    public int example1() {
        int i = compute(); // might throw
        markComputationDone();
        return i; // PMD complains that variable could be avoided
    }

    public int example2() {
        Mutable m = new Mutable();
        int i = compute(m);
        sideEffect(m);
        return i;
    }
    static void sideEffect(Mutable m) {}
    static int sideEffect(Mutable m) {}
    static int compute() {}
    static int markComputationDone() {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1775 [java] False negative in UnnecessaryLocalBeforeReturn when splitting statements across multiple lines</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class UnnecessaryLocalBeforeReturnFP {
    public Object test2() {
        int i = 0;
        Object o = thing()
            .make(i);
        return o; // true positive
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1804 [java] NPE with fields</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class ObjectCreator {

    private static final String A = "";
    private static final String B = "" + A; // the existence of this line causes the NPE.

    public Object create() {
        final Object o = new Object(A);
        return o;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>FP with captured method reference</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.util.function.Supplier;
public class ObjectCreator {
    public Supplier<String> create() {
        final Object o = new Object(); // captured by the method ref
        return o::toString;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>FN with lambdas #3275</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>5</expected-linenumbers>
        <code><![CDATA[
import java.util.concurrent.Callable;

public class UnnecessaryLocal {
    void foo() {
        Callable<String> c = () -> { String s = "1"; return s; };
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>FN with anonymous classes #3275</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>7</expected-linenumbers>
        <code><![CDATA[
import java.util.concurrent.Callable;

public class UnnecessaryLocal {
    void foo() {
        Callable<String> c = new Callable<>() {
            public String call() {
                String s = "1";
                return s;
            }
        };
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloneThrowsCloneNotSupportedException.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>ok, throws CloneNotSupportedException</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void clone() throws CloneNotSupportedException {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>bad</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    void clone() {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>final class, rule does not apply</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public final class Foo {
    void clone() {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>testing with multiple methods</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    void clone() {}
    void foo() {}
    void bar() {}
}
        ]]></code>
    </test-code>
</test-data>
