=== pmd/pmd/pmd-test-schema/src/main/resources/net/sourceforge/pmd/test/schema/rule-tests_1_0_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://pmd.sourceforge.net/rule-tests"
        targetNamespace="http://pmd.sourceforge.net/rule-tests"
        elementFormDefault="qualified">

    <element name="test-data">
        <complexType>
            <choice maxOccurs="unbounded">
                <element name="test-code" minOccurs="0" maxOccurs="unbounded" type="tns:testType"/>
                <element name="code-fragment" minOccurs="0" maxOccurs="unbounded" type="tns:codeFragmentType">
                    <annotation>
                        <documentation>
                            A code fragment that can be referred to by several tests.
                        </documentation>
                    </annotation>
                </element>
            </choice>
        </complexType>
    </element>

    <complexType name="testType">
        <sequence>
            <element name="description" type="string"/>
            <element name="rule-property" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <simpleContent>
                        <extension base="string">
                            <attribute name="name" type="string" use="required"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>

            <element name="expected-problems" type="nonNegativeInteger"/>
            <element name="expected-linenumbers" type="string" minOccurs="0"/>
            <element name="expected-messages" minOccurs="0">
                <complexType>
                    <sequence>
                        <element name="message" type="string" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
            <choice>
                <element name="code" type="string"/>
                <element name="code-ref">
                    <complexType>
                        <attribute name="id" type="IDREF" use="required"/>
                    </complexType>
                </element>
            </choice>
            <element name="source-type" minOccurs="0" default="" type="string">
                <annotation>
                    <documentation>
                        Language version of the source, eg 'java 8'.
                    </documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="reinitializeRule" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="regressionTest" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated. Use "disabled" instead.
                    If this attribute is set to "false", then the test is ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="useAuxClasspath" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>

        <attribute name="disabled" type="boolean" default="false">
            <annotation>
                <documentation>
                    A reason why the test is disabled/ignored should be provided as a comment for the test.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="focused" type="boolean" default="false">
            <annotation>
                <documentation>
                    If true, only this test will be executed, and all others will be disabled.
                    If several tests in the same file are focused, then the last one wins, in
                    document order.
                    This attribute is provided as a way for developers to temporarily focus on a single test.
                    Test files with a focused test should not be checked in. For this reason,
                    using this attribute produces a warning.
                </documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="codeFragmentType">
        <simpleContent>
            <extension base="string">
                <attribute name="id" type="ID" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnit4TestShouldUseBeforeAnnotation.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Contains setUp</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
import org.junit.Test;
public class Foo {
    public void setUp() {
    }
    @Test
    public void foo() {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Contains @setUp</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import org.junit.Before;
import org.junit.Test;
public class Foo {
    @Before
    public void setUp() {
    }
    @Test
    public void foo() {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Renamed setup</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import org.junit.Before;
import org.junit.Test;
public class Foo {
    @Before
    public void configure() {
    }
    @Test
    public void foo() {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1400 False positive with JUnit4TestShouldUseBeforeAnnotation</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import org.junit.Before;
import org.junit.Test;
import my.EsSetup;
public class Foo {
    EsSetup esSetup;
    @Before("@ResetEsSetup")
    public void setUp() {
        esSetup.execute(EsSetup.deleteAll());
    }
    @Test
    public void someTest() {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1446 False positive with JUnit4TestShouldUseBeforeAnnotation when TestNG is used</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import java.lang.reflect.Method;

public class Foo {
    @BeforeMethod
    public void setUp(Method m) {
      //...
    }
    @Test
    public void someTest() {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#940 False positive with JUnit4TestShouldUseBeforeAnnotation when JUnit5's 'BeforeEach' is used</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import org.junit.jupiter.api.*;

public class Foo {
    @BeforeEach
    public void setUp() {
      //...
    }
    @Test
    public void someTest() {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#940 False positive with JUnit4TestShouldUseBeforeAnnotation when JUnit5's 'BeforeAll' is used</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import org.junit.jupiter.api.*;

public class Foo {
    @BeforeAll
    public void setUp() {
      //...
    }
    @Test
    public void someTest() {}
}
        ]]></code>
    </test-code>
    <test-code>
        <description>Contains setUp, not a junit 4 test</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            public class Foo {
                public void setUp() {
                }
                public void foo() {
                }
            }
            ]]></code>
    </test-code>
    <test-code>
        <description>Contains setUp with different signature</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            import org.junit.Test;

            public class Foo {

                public void setUp(int something) {
                }

                @Test
                public void foo() {
                }
            }
            ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/EmptyStatementBlock.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>failure case</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>statement block not empty</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        { return; }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>not a statement block</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {
        if (true) {
            return;
        }
    }
}
        ]]></code>
    </test-code>
    <test-code>
        <description>block in switch case</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>4</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    public void bar() {
        switch (1) {
        case 2: { }
        }
    }
}
        ]]></code>
    </test-code>
    <test-code>
        <description>block in switch case (arrow)</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>4</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    public void bar() {
        switch (1) {
        case 2 -> { }
        }
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/naming/xml/ShortClassName.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">
    <test-code>
        <description><![CDATA[
ShortClassName basic test case
     ]]></description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {

}
     ]]></code>
    </test-code>

    <test-code>
        <description><![CDATA[
ShortClassName basic test case 2 : More code and other declarations
     ]]></description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class NotFoo {

	public void m() {
		String bar;
		int x;
	}
	
	private class ValidName {
	
	}
}
     ]]></code>
    </test-code>

    <test-code>
        <description><![CDATA[
ShortClassName works with private classes.
     ]]></description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class YetAnotherFoo {
	
	private class bar {
	
	}
}
     ]]></code>
    </test-code>
    <test-code>
        <description>#1143 ShortClassName fires with a 5-letter class name</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Timer {
}
        ]]></code>
    </test-code>
    <test-code>
        <description>#1232 Make ShortClassName configurable (default = 5)</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>2</expected-linenumbers>
        <expected-messages>
            <message>Avoid short class names like Bar</message>
        </expected-messages>
        <code><![CDATA[
public class ThisIsALongName { }
class Bar { }
        ]]></code>
    </test-code>
    <test-code>
        <description>#1232 Make ShortClassName configurable (minimum length = 2)</description>
        <rule-property name="minimum">2</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class ThisIsALongName { }
class Bar { }
        ]]></code>
    </test-code>
    <test-code>
        <description>#1232 Make ShortClassName configurable (minimum length = 4)</description>
        <rule-property name="minimum">4</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Isbn { }
class Card { }
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableNamingConventions.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
        xmlns="http://pmd.sourceforge.net/rule-tests"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Default is camel case</description>
        <expected-problems>3</expected-problems>
        <expected-messages>
            <message>The local variable name 'Foo' doesn't match '[a-z][a-zA-Z0-9]*'</message>
            <message>The final local variable name 'Hoo' doesn't match '[a-z][a-zA-Z0-9]*'</message>
            <message>The exception block parameter name 'E' doesn't match '[a-z][a-zA-Z0-9]*'</message>
        </expected-messages>
        <code><![CDATA[
public class Bar {
    {
        int Foo;
        final int Hoo;

        try {

        } catch (Exception E) {

        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Test local variable property</description>
        <rule-property name="localVarPattern">[A-Z][A-Z0-9]+</rule-property>
        <expected-problems>3</expected-problems>
        <expected-messages>
            <message>The local variable name 'Foo' doesn't match '[A-Z][A-Z0-9]+'</message>
            <message>The final local variable name 'Hoo' doesn't match '[a-z][a-zA-Z0-9]*'</message>
            <message>The exception block parameter name 'E' doesn't match '[a-z][a-zA-Z0-9]*'</message>
        </expected-messages>
        <code><![CDATA[
public class Bar {
    {
        int Foo;
        int FOO; // that's ok
        final int Hoo;

        try {

        } catch (Exception E) {

        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Test final local variable property</description>
        <rule-property name="finalVarPattern">[A-Z][A-Z0-9]+</rule-property>
        <expected-problems>3</expected-problems>
        <expected-messages>
            <message>The local variable name 'Foo' doesn't match '[a-z][a-zA-Z0-9]*'</message>
            <message>The final local variable name 'Hoo' doesn't match '[A-Z][A-Z0-9]+'</message>
            <message>The exception block parameter name 'E' doesn't match '[a-z][a-zA-Z0-9]*'</message>
        </expected-messages>
        <code><![CDATA[
public class Bar {
    {
        int Foo;
        final int FOO; // that's ok
        final int Hoo;

        try {

        } catch (Exception E) {

        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Test exception parameter property</description>
        <rule-property name="catchParameterPattern">[A-Z][A-Z0-9]+</rule-property>
        <expected-problems>3</expected-problems>
        <expected-messages>
            <message>The local variable name 'Foo' doesn't match '[a-z][a-zA-Z0-9]*'</message>
            <message>The final local variable name 'Hoo' doesn't match '[a-z][a-zA-Z0-9]*'</message>
            <message>The exception block parameter name 'Eff' doesn't match '[A-Z][A-Z0-9]+'</message>
        </expected-messages>
        <code><![CDATA[
public class Bar {
    {
        int Foo;
        final int Hoo;

        try {

        } catch (Exception Eff) {

        }

        try {

        } catch (Exception EFF) { // that's ok

        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>One character for loop variables should be ok by default</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.util.*;
public class LocalVarNamingConvention {
    public void bar() {
        for (int i = 0; i < 10; i++) { }

        List<String> data = Arrays.asList("a", "b");
        for (String s : data) { }
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidCallingFinalize.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
        xmlns="http://pmd.sourceforge.net/rule-tests"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>simple failure case</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void foo () {
        finalize();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>calling finalize on an object</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>4</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void foo () {
        Foo f;
        f.finalize();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>calling super.finalize</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void foo () {
        super.finalize();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>no call to finalize</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void finalize () {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>it's ok in a finalizer</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void finalize () {
        super.finalize();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>finalizer in anon inner class is OK too</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void foo () {
        Foo myFoo = new Foo(new FooOtherInterface() {
            protected void finalize() {
                super.finalize();
            }
        });
    }

    interface FooOtherInterface { }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1440 NPE in AvoidCallingFinalize</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
public class InputFinalize {
    {
        super.finalize();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>overloaded finalize is ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void foo() {
        finalize("hello", "world");
    }

    public void finalize(String ... args) {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>variable name false-positive test</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    private int finalize;

    public void bar() {
        finalize++;
        return finalize;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>super.finalize in constructor false-negative test</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>4</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    public Foo() throws Throwable {
        super.equals(new String());
        super.finalize();
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/errorprone/xml/AvoidDirectAccessTriggerMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Directly accessing the Trigger.old map.</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
trigger AccountTrigger on Account (before insert, before update) {
   Account a = Trigger.new[0]; //Bad: Accessing the trigger array directly is not recommended.
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Looping through map, best practice</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
trigger AccountTrigger on Account (before insert, before update) {
   for ( Account a : Trigger.new ){
        //Good: Iterate through the trigger.new array instead.
        System.debug(a);
   }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Regression issue #792</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
class NotATrigger {
   void foo(){
        Account[] accounts = opportunity.Accounts[0];
   }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UnconditionalIfStatement.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>if (true)</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void bar() {
        if (true) {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>if (false)</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void bar() {
        if (false) {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>no constant folding</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    private static final boolean DEBUG = "false";
    void bar() {
        if (DEBUG) {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>short circuit operator</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar(Object x, boolean y) {
        if (y == true) {}
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/security/xml/HardCodedCryptoKey.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Hard coded inline cryptographic key, bad</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>6</expected-linenumbers>
        <code><![CDATA[
import javax.crypto.spec.SecretKeySpec;

public class Foo {

    void encrypt() {
        SecretKeySpec keySpec =  new SecretKeySpec("hard coded key here".getBytes("UTF-8"), "AES");
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Key stored in a property, good</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import javax.crypto.spec.SecretKeySpec;

public class SecureProperty {
    byte[] getKeyBytes() {return null;}
    void encrypt(SecureProperty secureProperty) {
        SecretKeySpec keySpec =  new SecretKeySpec(secureProperty.getKeyBytes(), "AES");
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Hard coded in field cryptographic key, bad</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>5</expected-linenumbers>
        <code><![CDATA[
import javax.crypto.spec.SecretKeySpec;

public class Foo {

    static private String key = "0123456789ABCDEF";

    void encrypt() {
        byte[] keyData = key.getBytes("UTF-8");

        SecretKeySpec keySpec =  new SecretKeySpec(keyData, "AES");
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Hard coded crypto key byte[], bad</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
import javax.crypto.spec.SecretKeySpec;

public class Foo {

    static private byte[] encryptionKey = new byte[] { 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00 };

    void encrypt() {
        SecretKeySpec keySpec =  new SecretKeySpec(encryptionKey, "AES");
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Key fetched from a property, good</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import javax.crypto.spec.SecretKeySpec;
import my.SecureUtils;
import my.Struct;
public class Foo {

    void encrypt(Struct data) {
        byte[] computedSecretKey = SecureUtils.computeSecretKey(data.getSecretKeyAlgorithm(),
            data.getAccessKey(), data.getClientIp(), data.getTimeStamp(), data.getEnv());
        SecretKeySpec secretKeySpec = new SecretKeySpec(computedSecretKey, data.getSecretKeyAlgorithm().getName());
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>[java] HardcodedCryptoKey false negative with variable assignments #3368</description>
        <expected-problems>3</expected-problems>
        <expected-linenumbers>7,9,16</expected-linenumbers>
        <code><![CDATA[
import javax.crypto.spec.SecretKeySpec;

public class Foo {
    public void testHardCodedCryptoKey(boolean tag) {
       String str;
       if (tag) {
          str = "Hardcoded Crypto Key1"; // should report a warning here
       } else {
          str = "Hardcoded Crypto Key2"; // should report a warning here
       }
       SecretKeySpec secretKeySpec = new SecretKeySpec(str.getBytes(), "AES");
    }

    void encrypt() {
        final String var0;
        var0 = "hard coded key here";
        SecretKeySpec keySpec =  new SecretKeySpec(var0.getBytes(), "AES");
    }

    void encrypt2(String prefix, String key) {
        final String var0 = prefix;
        var0 = var0 + key;
        SecretKeySpec keySpec =  new SecretKeySpec(var0.getBytes(), "AES");
    }
}
        ]]></code>
    </test-code>
</test-data>
