=== pmd/pmd/pmd-test-schema/src/main/resources/net/sourceforge/pmd/test/schema/rule-tests_1_0_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://pmd.sourceforge.net/rule-tests"
        targetNamespace="http://pmd.sourceforge.net/rule-tests"
        elementFormDefault="qualified">

    <element name="test-data">
        <complexType>
            <choice maxOccurs="unbounded">
                <element name="test-code" minOccurs="0" maxOccurs="unbounded" type="tns:testType"/>
                <element name="code-fragment" minOccurs="0" maxOccurs="unbounded" type="tns:codeFragmentType">
                    <annotation>
                        <documentation>
                            A code fragment that can be referred to by several tests.
                        </documentation>
                    </annotation>
                </element>
            </choice>
        </complexType>
    </element>

    <complexType name="testType">
        <sequence>
            <element name="description" type="string"/>
            <element name="rule-property" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <simpleContent>
                        <extension base="string">
                            <attribute name="name" type="string" use="required"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>

            <element name="expected-problems" type="nonNegativeInteger"/>
            <element name="expected-linenumbers" type="string" minOccurs="0"/>
            <element name="expected-messages" minOccurs="0">
                <complexType>
                    <sequence>
                        <element name="message" type="string" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
            <choice>
                <element name="code" type="string"/>
                <element name="code-ref">
                    <complexType>
                        <attribute name="id" type="IDREF" use="required"/>
                    </complexType>
                </element>
            </choice>
            <element name="source-type" minOccurs="0" default="" type="string">
                <annotation>
                    <documentation>
                        Language version of the source, eg 'java 8'.
                    </documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="reinitializeRule" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="regressionTest" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated. Use "disabled" instead.
                    If this attribute is set to "false", then the test is ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="useAuxClasspath" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>

        <attribute name="disabled" type="boolean" default="false">
            <annotation>
                <documentation>
                    A reason why the test is disabled/ignored should be provided as a comment for the test.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="focused" type="boolean" default="false">
            <annotation>
                <documentation>
                    If true, only this test will be executed, and all others will be disabled.
                    If several tests in the same file are focused, then the last one wins, in
                    document order.
                    This attribute is provided as a way for developers to temporarily focus on a single test.
                    Test files with a focused test should not be checked in. For this reason,
                    using this attribute produces a warning.
                </documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="codeFragmentType">
        <simpleContent>
            <extension base="string">
                <attribute name="id" type="ID" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codesize/xml/StdCyclomaticComplexity.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">
    <code-fragment id="basic-violation">
    <![CDATA[
public class Foo {
 public void example() {
  int x = 0;
  int a = 0;
  int b = 0;
  int c = 0;
  int d = 0;
  int a1 = 0;
  int a2 = 0;
  int b1 = 0;
  int b2 = 0;
  int z = 0;
  int h = 0;
  int e = 0;
  int f = 0;

  if (a == b) {
      if (a1 == b1) {
   x = 2;
      } else if (a2 == b2) {
   x = 2;
      } else {
   x = 2;
      }
  } else if (c == d) {
      while (c == d) {
   x = 2;
      }
  } else if (e == f) {
      for (int n = 0; n < h; n++) {
   x = 2;
      }
  } else {
      switch (z) {
      case 1:
   x = 2;
   break;

      case 2:
   x = 2;
   break;

      case 3:
   x = 2;
   break;

      default:
   x = 2;
   break;
      }
  }
 }
}
     ]]>
    </code-fragment>
    <test-code>
        <description>Simple method</description>
        <rule-property name="reportLevel">1</rule-property>
        <expected-problems>2</expected-problems>
        <expected-messages>
            <message>The class 'Foo' has a Standard Cyclomatic Complexity of 2 (Highest = 1).</message>
            <message>The method 'foo' has a Standard Cyclomatic Complexity of 1.</message>
        </expected-messages>
        <code><![CDATA[
public class Foo {
 public void foo() {}
}
     ]]></code>
    </test-code>
    <test-code>
        <description>Simple method</description>
        <rule-property name="reportLevel">10</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
 public void foo() {}
}
     ]]></code>
    </test-code>
    <test-code>
        <description>Complicated method</description>
        <rule-property name="reportLevel">10</rule-property>
        <expected-problems>2</expected-problems>
        <expected-messages>
            <message>The class 'Foo' has a Standard Cyclomatic Complexity of 12 (Highest = 11).</message>
            <message>The method 'example' has a Standard Cyclomatic Complexity of 11.</message>
        </expected-messages>
        <code-ref id="basic-violation"/>
    </test-code>
    <test-code>
        <description>Constructor</description>
        <rule-property name="reportLevel">1</rule-property>
        <expected-problems>2</expected-problems>
        <expected-messages>
            <message>The class 'Foo' has a Standard Cyclomatic Complexity of 2 (Highest = 1).</message>
            <message>The constructor 'Foo' has a Standard Cyclomatic Complexity of 1.</message>
        </expected-messages>
        <code><![CDATA[
public class Foo {
 public Foo() {}
}
     ]]></code>
    </test-code>
    <test-code>
        <description>Testing new parameter showClassMethods</description>
        <rule-property name="showClassesComplexity">false</rule-property>
        <expected-problems>1</expected-problems>
       <code-ref id="basic-violation"/>
    </test-code>
    <test-code>
        <description>Testing new parameter showMethodsMethods</description>
        <rule-property name="showMethodsComplexity">false</rule-property>
        <expected-problems>1</expected-problems>
       <code-ref id="basic-violation"/>
    </test-code>
  <test-code>
        <description>Testing default value of showClassMethods and showClassesComplexity</description>
        <expected-problems>2</expected-problems>
       <code-ref id="basic-violation"/>
    </test-code>
    <code-fragment id="constructor-violation"><![CDATA[
public class Test {
  public Test() {
    if (a == 1) {
      if (b == 2) {
        System.out.println("b");
      } else if (b == 1) {
      }
    } else {
    }
  }
}
    ]]></code-fragment>
    <test-code>
        <description>#984 Cyclomatic complexity should treat constructors like methods: 1 - showMethodsComplexity=true</description>
        <rule-property name="showClassesComplexity">false</rule-property>
        <rule-property name="showMethodsComplexity">true</rule-property>
        <rule-property name="reportLevel">1</rule-property>
        <expected-problems>1</expected-problems>
        <code-ref id="constructor-violation"/>
    </test-code>
    <test-code>
        <description>#984 Cyclomatic complexity should treat constructors like methods: 2 - showMethodsComplexity=false</description>
        <rule-property name="showClassesComplexity">false</rule-property>
        <rule-property name="showMethodsComplexity">false</rule-property>
        <rule-property name="reportLevel">1</rule-property>
        <expected-problems>0</expected-problems>
        <code-ref id="constructor-violation"/>
    </test-code>
    <test-code reinitializeRule="true">
        <description>#985 Suppressed methods shouldn't affect avg CyclomaticComplexity</description>
        <rule-property name="reportLevel">2</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Test {
  @SuppressWarnings("PMD.StdCyclomaticComplexity")
  public Test() {
    if (a == 1) {
      if (b == 2) {
        System.out.println("b");
      } else if (b == 1) {
      }
    } else {
    }
  }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/FieldDeclarationsShouldBeAtStartOfClass.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>basic test</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class HelloWorldBean {
    private String _thing;

    public String getMessage() {
        return "Hello World!";
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>basic test, not OK</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class HelloWorldBean {

    public String getMessage() {
        return "Hello World!";
    }
    private String _fieldInWrongLocation;
}
        ]]></code>
    </test-code>

    <test-code>
        <description>inner class, OK</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class HelloWorldBean {

    public String getMessage() {
        return "Hello World!";
    }

    public class Foo {
        private String _fieldInWrongLocation;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Initial report where rule was introduced, [ 2487971 ] False positive with field-level annotations</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import org.springframework.beans.factory.annotation.Autowired;
public class MyTest {
    @Autowired
    protected String _first;
    @Autowired
    protected String _second;
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Empty declaration is allowed</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.util.logging.Logger;
public class Foo {
    private static final Logger LOGGER = Logger.getLogger(Foo.class);

    ;

    private int id;
    private Foo myType;
    private String name;

    // OK, now constructors, getters, setters, etc.
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1126 False positive with FieldDeclarationsShouldBeAtStartOfClass for static enums</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.util.logging.Logger;
public class Foo {
    private static final Logger LOGGER = Logger.getLogger(Foo.class);

    public static enum MyType {
        ABC, DEF, GHI, JHK
    }

    private int id;
    private MyType myType;
    private String name;

    // OK, now constructors, getters, setters, etc.
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1126 Do not ignore enums</description>
        <rule-property name="ignoreEnumDeclarations">false</rule-property>
        <expected-problems>3</expected-problems>
        <code><![CDATA[
import java.util.logging.Logger;
public class Foo {
    private static final Logger LOGGER = Logger.getLogger(Foo.class);

    public static enum MyType {
        ABC, DEF, GHI, JHK
    }

    private int id;
    private MyType myType;
    private String name;

    // OK, now constructors, getters, setters, etc.
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1244 FieldDeclarationsShouldBeAtStartOfClass and anonymous classes, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class MyClass {
    private final String name;
    public MyClass() {
        this.name = "whatever";
    }
    public void onCreate() {
        // someView.setListener(onSomeViewClick);
    }
    private final OnClickListener onSomeViewClick = new OnClickListener() {
        @Override
        public void onClick(Object view) {
            // something
        }
    };
}
interface OnClickListener { void onClick(Object view); }
        ]]></code>
    </test-code>

    <test-code>
        <description>#1244 FieldDeclarationsShouldBeAtStartOfClass and anonymous classes, fail</description>
        <rule-property name="ignoreAnonymousClassDeclarations">false</rule-property>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>9</expected-linenumbers>
        <code><![CDATA[
public class MyClass {
    private final String name;
    public MyClass() {
        this.name = "whatever";
    }
    public void onCreate() {
        // someView.setListener(onSomeViewClick);
    }
    private final OnClickListener onSomeViewClick = new OnClickListener() {
        @Override
        public void onClick(Object v) {
            // something
        }
    };
}
interface OnClickListener { void onClick(Object view); }
        ]]></code>
    </test-code>

    <test-code>
        <description>#1354 Complex FieldDeclarationsShouldBeAtStartOfClass false positive with Spring annotations</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Bean;
public class MyClass {
    private static final String MY_STRING = "STRING";

    @Autowired
    private MyPrivate myPrivate;

    @Bean
    public void myPublicBean() {}

    private static void myPrivateStatic() {}
    static class MyPrivate {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1364 FieldDeclarationsShouldBeAtStartOfClass false positive using multiple annotations</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import javax.persistence.ManyToOne;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
public class MyEntity {

    private static final String MY_STRING = "STRING";

    @Id
    @Column
    private Long id;

    @ManyToOne
    @JoinColumn("")
    private MyEntity relation;

    public MyEntity() {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#345 [java] FieldDeclarationsShouldBeAtStartOfClass: Add ability to ignore interfaces - default case</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>6</expected-linenumbers>
        <code><![CDATA[
public class TestFieldDeclarations {
    public interface StartCaptureListener {
        void onStartCapture(boolean shouldUploadMediaToTba);
    }

    private static final int TAKE_PHOTO_RC = 334; // line 6
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#345 [java] FieldDeclarationsShouldBeAtStartOfClass: Add ability to ignore interfaces - ignore interfaces</description>
        <rule-property name="ignoreInterfaceDeclarations">true</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class TestFieldDeclarations {
    public interface StartCaptureListener {
        void onStartCapture(boolean shouldUploadMediaToTba);
    }

    private static final int TAKE_PHOTO_RC = 334; // line 6
}
        ]]></code>
    </test-code>

    <test-code>
        <description>False negative with anon classes (1)</description>
        <rule-property name="ignoreAnonymousClassDeclarations">false</rule-property>
        <expected-problems>3</expected-problems>
        <expected-linenumbers>4,5,7</expected-linenumbers>
        <code><![CDATA[
public class TestFieldDeclarations {
    class Inner {
        void method1() { }
        private int field1; // violation 1
        private Inner anon = new Inner() { // violation 2 - field "anon"
            void method2() { }
            private int field2; // violation 3
        };
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>False negative with anon classes (2)</description>
        <rule-property name="ignoreAnonymousClassDeclarations">true</rule-property>
        <expected-problems>2</expected-problems>
        <expected-linenumbers>4,7</expected-linenumbers>
        <code><![CDATA[
public class TestFieldDeclarations {
    class Inner {
        void method1() { }
        private int field1; // violation 1
        private Inner anon = new Inner() { // ignored due to ignoreAnonymousClassDeclarations
            void method2() { }
            private int field2; // violation 2
        };
    }
}
        ]]></code>
    </test-code>


    <test-code>
        <description>Initializers don't count</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            public class MyClass {
                private static final String NAME;
                static {
                    NAME = "";
                }

                private final String name;
                {
                    name = "";
                }
                private String name2;

                public MyClass() {
                    this.name = "whatever";
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>Check inside enums</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            public enum MyClass {
                A,
                B;

                private final String name;

                public MyClass() {
                    this.name = "whatever";
                }
            }
            ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/multithreading/xml/DoNotUseThreads.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Having thread in a type name is doubtfull but allowed</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class UsingThread  {
}
        ]]></code>
    </test-code>

    <test-code>
        <description>extending threads is not allowed</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>2</expected-linenumbers>
        <code><![CDATA[
// This is not allowed
public class UsingThread extends Thread {
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Implementing ExecutorService is not allowed</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
import java.util.concurrent.ExecutorService;

public class PMDTestExecutorService implements ExecutorService {}
        ]]></code>
    </test-code>

    <test-code>
        <description>Extending AbstractExecutorService is not allowed</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
import java.util.concurrent.*;

public class PMDTestExecutorService extends AbstractExecutorService {}
        ]]></code>
    </test-code>

    <test-code>
        <description>Using ExecutorService is not allowed</description>
        <expected-problems>2</expected-problems>
        <expected-linenumbers>6,7</expected-linenumbers>
        <code><![CDATA[
import java.util.concurrent.Executors;
import java.util.concurrent.ExecutorService;

public class ExecutorServiceUsage {
    public void executor_service_method_invocation() {
        ExecutorService executorService = Executors.newSingleThreadExecutor();
        executorService.submit(new Runnable() {
             @Override
             public void run() {
             }
        });
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Using Executors directly is not allowed</description>
        <expected-problems>2</expected-problems>
        <expected-linenumbers>6,11</expected-linenumbers>
        <code><![CDATA[
import java.util.concurrent.Executors;
import java.util.concurrent.Callable;

public class ExecutorsUsage {
    public void static_usage_of_Executors() {
         Executors.newSingleThreadExecutor().submit(new Runnable() {
             @Override
             public void run() {
             }
        });
        Executors.newFixedThreadPool(1).submit(new Callable<Object>() {
            @Override
            public Object call() throws Exception {
                return null;
            }
        });
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Implementing Runnable is not forbidden see https://github.com/pmd/pmd/issues/1627</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class OtherThread implements Runnable {}
        ]]></code>
    </test-code>

    <test-code>
        <description>Use of Runnable is also not forbidden see https://github.com/pmd/pmd/issues/1627</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Violation {
    public void method() {
            Runnable runnable = new Runnable() {
                @Override
                public void run() {

                }
            };
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>getContextClassLoader is ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Ok {
    ClassLoader cl = Thread.currentThread().getContextClassLoader();
}
        ]]></code>
    </test-code>

    <test-code>
        <description>[java] DoNotUseThreads report duplicate warnings #4210</description>
        <expected-problems>2</expected-problems>
        <expected-linenumbers>2,4</expected-linenumbers>
        <code><![CDATA[
public final class Test {
    public final Thread BAR = new Thread();  // reports two duplicate warnings in this line, but one is enough

    public Thread getBAR() {  // report one warning in this line
        return this.BAR;
    }
}
]]></code>
    </test-code>

    <test-code>
        <description>False negatives with field declarations</description>
        <expected-problems>19</expected-problems>
        <expected-linenumbers>6,7,8,9,13,14,20,26,30,31,33,34,37,38,42,43,47,48,51</expected-linenumbers>
        <code><![CDATA[
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ThreadFactory;

class DoNotUseThreadsTest {
    private Thread background;                           // 6: violation expected
    private ScheduledExecutorService scheduledExecutor;  // 7: violation expected
    private ForkJoinPool pool;                           // 8: violation expected
    private final Thread owner = Thread.currentThread(); // 9: violation expected

    static final ThreadFactory threadFactory1 = new ThreadFactory() {
        @Override
        public Thread newThread(final Runnable r) {      // 13: violation expected
            return new Thread(r);                        // 14: violation expected
        }
    };

    static final ThreadFactory threadFactory2 = new ThreadFactory() {
        @Override
        public Thread newThread(final Runnable r) {      // 20: violation expected
            return null;
        }
    };

    DoNotUseThreadsTest() {
        this.background = new Thread();                  // 26: violation expected
    }

    public void run() {
        new Thread(() -> System.out.println("foo")).start(); // 30: violation expected
        Thread t2 = new Thread();                            // 31: one violation expected
        // report two violations, if on two separate lines
        Thread t3 =                                          // 33: violation expected
            new Thread();                                    // 34: violation expected
    }

    public Thread getThread() {                         // 37: violation expected
        return new Thread();                            // 38: violation expected
    }

    @Override
    public Thread getThread1() {                        // 42: violation expected
        return new Thread();                            // 43: violation expected
    }

    @Override
    public Thread getThread2(final Runnable r) {        // 47: violation expected
        return new Thread(r);                           // 48: violation expected
    }

    private static class MyThread extends Thread { }    // 51: violation expected
}
]]></code>
    </test-code>

    <test-code>
        <description>More false negatives</description>
        <expected-problems>2</expected-problems>
        <expected-linenumbers>5,8</expected-linenumbers>
        <code><![CDATA[
import java.util.HashMap;
import java.util.Map;

class DoNotUseThreadsTest {
    Map<Thread, String> m = new HashMap<>();

    boolean isThread(Class<?> cl) {
        return cl == Thread.class;
    }
}
]]></code>
    </test-code>

    <test-code>
        <description>Static method calls like Thread.onSpinWait() should not trigger the rule - issue #6520</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class OnSpinWaitExample {
    public void foo() {
        java.lang.Thread.onSpinWait();
    }
    
    public void bar() {
        Thread.onSpinWait();
    }
}
]]></code>
    </test-code>
</test-data>
