=== pmd/pmd/pmd-core/src/main/resources/report_2_0_0.xsd
<?xml version="1.0"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://pmd.sourceforge.net/report/2.0.0"
  targetNamespace="http://pmd.sourceforge.net/report/2.0.0"
  elementFormDefault="qualified">

  <xs:element name="pmd">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="file" type="file" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="error" type="error" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="suppressedviolation" type="suppressedviolation" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="configerror" type="configerror" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="version" type="xs:string" use="required" />
      <xs:attribute name="timestamp" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="file">
    <xs:sequence>
      <xs:element name="violation" type="violation" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="violation">
    <xs:simpleContent>
      <xs:extension base="xs:string">
	    <xs:attribute name="beginline" type="xs:integer" use="required" />
	    <xs:attribute name="endline" type="xs:integer" use="required" />
	    <xs:attribute name="begincolumn" type="xs:integer" use="required" />
	    <xs:attribute name="endcolumn" type="xs:integer" use="required" />
	    <xs:attribute name="rule" type="xs:string" use="required" />
	    <xs:attribute name="ruleset" type="xs:string" use="required" />
	    <xs:attribute name="package" type="xs:string" use="optional" />
	    <xs:attribute name="class" type="xs:string" use="optional" />
	    <xs:attribute name="method" type="xs:string" use="optional" />
	    <xs:attribute name="variable" type="xs:string" use="optional" />
	    <xs:attribute name="externalInfoUrl" type="xs:string" use="optional" />
	    <xs:attribute name="priority" type="xs:string" use="required" />
	  </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="error">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="filename" type="xs:string" use="required"/>
        <xs:attribute name="msg" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="suppressedviolation">
    <xs:attribute name="filename" type="xs:string" use="required" />
    <xs:attribute name="suppressiontype" type="xs:string" use="required" />
    <xs:attribute name="msg" type="xs:string" use="required" />
    <xs:attribute name="usermsg" type="xs:string" use="required" />
  </xs:complexType>
  
   <xs:complexType name="configerror">
     <xs:attribute name="rule" type="xs:string" use="required" />
     <xs:attribute name="msg" type="xs:string" use="required" />
   </xs:complexType>
</xs:schema>

=== pmd/pmd/pmd-ant/src/test/resources/net/sourceforge/pmd/ant/xml/expected-pmd-ant-xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 https://pmd.github.io/schema/report_2_0_0.xsd" version="" timestamp="">
<file name="sample.dummy">
<violation beginline="1" endline="1" begincolumn="1" endcolumn="110" rule="SampleXPathRule" ruleset="Test Ruleset" package="foo" externalInfoUrl="${pmd.website.baseurl}/rules/dummy/basic.xml#SampleXPathRule" priority="3">
Test Rule 2
</violation>
<violation beginline="1" endline="1" begincolumn="1" endcolumn="110" rule="DeprecatedRule" ruleset="Test Ruleset" package="foo" externalInfoUrl="${pmd.website.baseurl}/rules/dummy/basic.xml#deprecatedrule" priority="3">
Test Rule 3
</violation>
</file>
<file name="sample2.dummy">
<violation beginline="1" endline="1" begincolumn="1" endcolumn="110" rule="SampleXPathRule" ruleset="Test Ruleset" package="foo" externalInfoUrl="${pmd.website.baseurl}/rules/dummy/basic.xml#SampleXPathRule" priority="3">
Test Rule 2
</violation>
<violation beginline="1" endline="1" begincolumn="1" endcolumn="110" rule="DeprecatedRule" ruleset="Test Ruleset" package="foo" externalInfoUrl="${pmd.website.baseurl}/rules/dummy/basic.xml#deprecatedrule" priority="3">
Test Rule 3
</violation>
</file>
<file name="sampleLexError.dummy">
<violation beginline="1" endline="1" begincolumn="1" endcolumn="30" rule="SampleXPathRule" ruleset="Test Ruleset" package="foo" externalInfoUrl="${pmd.website.baseurl}/rules/dummy/basic.xml#SampleXPathRule" priority="3">
Test Rule 2
</violation>
<violation beginline="1" endline="1" begincolumn="1" endcolumn="30" rule="DeprecatedRule" ruleset="Test Ruleset" package="foo" externalInfoUrl="${pmd.website.baseurl}/rules/dummy/basic.xml#deprecatedrule" priority="3">
Test Rule 3
</violation>
</file>
</pmd>
