=== pmd/pmd/pmd-core/src/main/resources/ruleset_2_0_0.xsd
<?xml version="1.0"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
  targetNamespace="http://pmd.sourceforge.net/ruleset/2.0.0"
  elementFormDefault="qualified">

  <xs:element name="ruleset">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="exclude-pattern" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="include-pattern" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="rule" type="rule" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="rule">
    <xs:sequence>
      <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="priority" type="xs:int" default="5" minOccurs="0" maxOccurs="1"/>
      <xs:element name="properties" type="properties" minOccurs="0" maxOccurs="1" />
      <xs:element name="exclude" type="exclude" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="example" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="language" type="xs:string" use="optional" />
    <xs:attribute name="minimumLanguageVersion" type="xs:string" use="optional" />
    <xs:attribute name="maximumLanguageVersion" type="xs:string" use="optional" />
    <xs:attribute name="name" type="xs:ID" use="optional" />
    <xs:attribute name="since" type="xs:string" use="optional" />
    <xs:attribute name="ref" type="xs:string" use="optional" />
    <xs:attribute name="message" type="xs:string" use="optional" />
    <xs:attribute name="externalInfoUrl" type="xs:string" use="optional" />
    <xs:attribute name="class" type="xs:NMTOKEN" use="optional" />
    <xs:attribute name="dfa" type="xs:boolean" use="optional" />  <!-- rule uses dataflow analysis -->
    <xs:attribute name="typeResolution" type="xs:boolean" default="false" use="optional" />
    <xs:attribute name="deprecated" type="xs:boolean" default="false" use="optional" />
  </xs:complexType>

  <xs:complexType name="properties">
    <xs:sequence>
      <xs:element name="property" type="property" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="property">
    <xs:sequence>
      <xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
    <xs:attribute name="value" type="xs:string" use="optional" />
    <xs:attribute name="description" type="xs:string" use="optional" />
    <xs:attribute name="type" type="xs:string" use="optional" />
    <xs:attribute name="delimiter" type="xs:string" use="optional" />
    <xs:attribute name="min" type="xs:string" use="optional" />
    <xs:attribute name="max" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:complexType name="exclude">
    <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
  </xs:complexType>

</xs:schema>

=== pmd/pmd/pmd-dist/src/test/resources/rulesets/all-apex.xml
<?xml version="1.0"?>

<ruleset name="All Apex Rules" 
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">
    <description>Every Apex Rule in PMD</description>

    <rule ref="category/apex/bestpractices.xml" />
    <rule ref="category/apex/codestyle.xml" />
    <rule ref="category/apex/design.xml" />
    <rule ref="category/apex/documentation.xml" />
    <rule ref="category/apex/errorprone.xml" />
    <rule ref="category/apex/multithreading.xml" />
    <rule ref="category/apex/performance.xml" />
    <rule ref="category/apex/security.xml" />

</ruleset>

=== pmd/pmd/pmd-core/src/test/resources/net/sourceforge/pmd/TestRuleset1.xml
<?xml version="1.0"?>
<ruleset name="Test Ruleset" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>
  Ruleset used by test net.sourceforge.pmd.RuleSetWriter and RuleSetFactoryTest
  </description>

    <rule name="MockRule1" language="dummy" since="1.0" message="Test Rule" class="net.sourceforge.pmd.lang.rule.MockRule"
        externalInfoUrl="${pmd.website.baseurl}/rules/test/TestRuleset1.xml#MockRule">
        <description>
Just for test
     </description>
        <priority>3</priority>
        <example>
 <![CDATA[
 ]]>
     </example>
    </rule>

    <rule name="MockRule2" language="dummy" since="1.0" message="Test Rule 2" class="net.sourceforge.pmd.lang.rule.MockRule"
        externalInfoUrl="${pmd.website.baseurl}/rules/test/TestRuleset1.xml#MockRule2">
        <description>
Just for test
     </description>
        <priority>3</priority>
        <example>
 <![CDATA[
 ]]>
     </example>
    </rule>

    <rule name="MockRule3" deprecated="true" ref="net/sourceforge/pmd/TestRuleset2.xml/TestRule"/>

    <rule name="MockRule4" language="dummy" since="1.0" message="Test Rule"
          class="net.sourceforge.pmd.lang.rule.XPathRule"
          externalInfoUrl="${pmd.website.baseurl}/rules/test/TestRuleset1.xml#MockRule">
        <description>
            Just for test
        </description>
        <priority>3</priority>
        <properties>
            <property name="test2" type="String" description="test 2" value="foo"/>
            <property name="test3" type="String" description="test 3" value="bar"/>
        </properties>
        <example>
            <![CDATA[
 ]]>
        </example>
    </rule>


    <rule name="TestRuleRef" ref="net/sourceforge/pmd/TestRuleset2.xml/TestRule"/>

</ruleset>

=== pmd/pmd/pmd-core/src/main/resources/rulesets/releases/700.xml
<?xml version="1.0"?>

<ruleset name="700"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">
  <description>
This ruleset contains links to rules that are new in PMD v7.0.0
  </description>

    <rule ref="category/apex/design.xml/UnusedMethod"/>

    <rule ref="category/java/codestyle.xml/UnnecessaryBoxing"/>

    <rule ref="category/kotlin/bestpractices.xml/FunctionNameTooShort"/>
    <rule ref="category/kotlin/errorprone.xml/OverrideBothEqualsAndHashcode"/>

    <rule ref="category/swift/errorprone.xml/ForceCast"/>
    <rule ref="category/swift/errorprone.xml/ForceTry"/>
    <rule ref="category/swift/bestpractices.xml/ProhibitedInterfaceBuilder"/>
    <rule ref="category/swift/bestpractices.xml/UnavailableFunction"/>

</ruleset>

=== pmd/pmd/pmd-dist/src/test/resources/rulesets/all-java.xml
<?xml version="1.0"?>

<ruleset name="All Java Rules" 
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">
    <description>Every Java Rule in PMD</description>

    <rule ref="category/java/bestpractices.xml" />
    <rule ref="category/java/codestyle.xml" />
    <rule ref="category/java/design.xml" />
    <rule ref="category/java/documentation.xml" />
    <rule ref="category/java/errorprone.xml" />
    <rule ref="category/java/multithreading.xml" />
    <rule ref="category/java/performance.xml" />
    <rule ref="category/java/security.xml" />

</ruleset>

=== pmd/pmd/pmd-java/src/main/resources/ruledefs/java/sunsecure.xml
<?xml version="1.0"?>

<ruleset name="Security Code Guidelines"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
  <description>
These rules check the security guidelines from Sun, published at http://java.sun.com/security/seccodeguide.html#gcg
  </description>

  <rule name="MethodReturnsInternalArray"
        since="2.2"
        message="Returning ''{0}'' may expose an internal array."
        class="net.sourceforge.pmd.lang.java.rule.sunsecure.MethodReturnsInternalArrayRule"
        externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_sunsecure.html#methodreturnsinternalarray">
    <description>
Exposing internal arrays to the caller violates object encapsulation since elements can be 
removed or replaced outside of the object that owns it. It is safer to return a copy of the array.
    </description>
    <priority>3</priority>
    <example>
<![CDATA[
public class SecureSystem {
    UserData [] ud;
    public UserData [] getUserData() {
        // Don't return directly the internal array, return a copy
        return ud;
    }
}
]]>
    </example>
  </rule>

  <rule name="ArrayIsStoredDirectly"
        since="2.2"
        message="The user-supplied array ''{0}'' is stored directly."
        class="net.sourceforge.pmd.lang.java.rule.sunsecure.ArrayIsStoredDirectlyRule"
        externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_sunsecure.html#arrayisstoreddirectly">
    <description>
Constructors and methods receiving arrays should clone objects and store the copy.
This prevents future changes from the user from affecting the original array.
    </description>
    <priority>3</priority>
    <example>
<![CDATA[
public class Foo {
    private String [] x;
        public void foo (String [] param) {
        // Don't do this, make a copy of the array at least
        this.x=param;
    }
}
]]>
    </example>
  </rule>

</ruleset>

=== pmd/pmd/pmd-java/src/main/resources/rulesets/java/j2ee.xml
<?xml version="1.0"?>

<ruleset name="J2EE"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

  <description>
Rules specific to the use of J2EE implementations.
  </description>

    <!-- Rules, that have been moved into a category -->
    <rule ref="category/java/errorprone.xml/DoNotTerminateVM" deprecated="true" />
    <rule ref="category/java/errorprone.xml/StaticEJBFieldShouldBeFinal" deprecated="true" />
    <rule ref="category/java/errorprone.xml/UseProperClassLoader" deprecated="true" />

    <rule ref="category/java/codestyle.xml/LocalHomeNamingConvention" deprecated="true" />
    <rule ref="category/java/codestyle.xml/LocalInterfaceSessionNamingConvention" deprecated="true" />
    <rule ref="category/java/codestyle.xml/MDBAndSessionBeanNamingConvention" deprecated="true" />
    <rule ref="category/java/codestyle.xml/RemoteInterfaceNamingConvention" deprecated="true" />
    <rule ref="category/java/codestyle.xml/RemoteSessionInterfaceNamingConvention" deprecated="true" />

    <rule ref="category/java/multithreading.xml/DoNotUseThreads" deprecated="true" />

</ruleset>

=== pmd/pmd/pmd-core/src/main/resources/rulesets/releases/36.xml
<?xml version="1.0"?>

<ruleset name="36"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">
  <description>
This ruleset contains links to rules that are new in PMD v3.6
  </description>

  <rule ref="rulesets/java/strings.xml/InefficientEmptyStringCheck"/>
  <!-- Removed with 7.0.0 <rule ref="rulesets/java/design.xml/UnsynchronizedStaticDateFormatter"/>-->
  <rule ref="rulesets/java/strings.xml/InsufficientStringBufferDeclaration"/>
<!--  <rule ref="rulesets/java/junit.xml/SimplifyBooleanAssertion"/>-->
  <rule ref="rulesets/java/basic.xml/AvoidThreadGroup"/>
  <rule ref="rulesets/jsp/basic-jsf.xml/DontNestJsfInJstlIteration"/>
  <rule ref="rulesets/jsp/basic.xml/NoLongScripts"/>
  <rule ref="rulesets/jsp/basic.xml/NoScriptlets"/>
  <rule ref="rulesets/jsp/basic.xml/NoInlineStyleInformation"/>
  <rule ref="rulesets/jsp/basic.xml/NoJspForward"/>
  <rule ref="rulesets/jsp/basic.xml/NoClassAttribute"/>
  <rule ref="rulesets/jsp/basic.xml/IframeMissingSrcAttribute"/>
  <rule ref="rulesets/jsp/basic.xml/NoHtmlComments"/>
</ruleset>
