=== pmd/pmd/pmd-core/src/main/resources/ruleset_2_0_0.xsd
<?xml version="1.0"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
  targetNamespace="http://pmd.sourceforge.net/ruleset/2.0.0"
  elementFormDefault="qualified">

  <xs:element name="ruleset">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="exclude-pattern" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="include-pattern" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="rule" type="rule" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="rule">
    <xs:sequence>
      <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="priority" type="xs:int" default="5" minOccurs="0" maxOccurs="1"/>
      <xs:element name="properties" type="properties" minOccurs="0" maxOccurs="1" />
      <xs:element name="exclude" type="exclude" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="example" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="language" type="xs:string" use="optional" />
    <xs:attribute name="minimumLanguageVersion" type="xs:string" use="optional" />
    <xs:attribute name="maximumLanguageVersion" type="xs:string" use="optional" />
    <xs:attribute name="name" type="xs:ID" use="optional" />
    <xs:attribute name="since" type="xs:string" use="optional" />
    <xs:attribute name="ref" type="xs:string" use="optional" />
    <xs:attribute name="message" type="xs:string" use="optional" />
    <xs:attribute name="externalInfoUrl" type="xs:string" use="optional" />
    <xs:attribute name="class" type="xs:NMTOKEN" use="optional" />
    <xs:attribute name="dfa" type="xs:boolean" use="optional" />  <!-- rule uses dataflow analysis -->
    <xs:attribute name="typeResolution" type="xs:boolean" default="false" use="optional" />
    <xs:attribute name="deprecated" type="xs:boolean" default="false" use="optional" />
  </xs:complexType>

  <xs:complexType name="properties">
    <xs:sequence>
      <xs:element name="property" type="property" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="property">
    <xs:sequence>
      <xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
    <xs:attribute name="value" type="xs:string" use="optional" />
    <xs:attribute name="description" type="xs:string" use="optional" />
    <xs:attribute name="type" type="xs:string" use="optional" />
    <xs:attribute name="delimiter" type="xs:string" use="optional" />
    <xs:attribute name="min" type="xs:string" use="optional" />
    <xs:attribute name="max" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:complexType name="exclude">
    <xs:attribute name="name" type="xs:NMTOKEN" use="required" />
  </xs:complexType>

</xs:schema>

=== pmd/pmd/pmd/rulesets/java/logging-java.xml
<?xml version="1.0"?>

<ruleset name="Java Logging"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd"
    xsi:noNamespaceSchemaLocation="http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

  <description>
The Java Logging ruleset contains a collection of rules that find questionable usages of the logger.
  </description>

    <rule name="MoreThanOneLogger"
    	   since="2.0"
         message="Class contains more than one logger."
         class="net.sourceforge.pmd.lang.java.rule.logging.MoreThanOneLoggerRule"
          externalInfoUrl="http://pmd.sourceforge.net/rules/java/logging-java.html#MoreThanOneLogger">
     <description>
Normally only one logger is used in each class.
     </description>
        <priority>2</priority>
     <example>
 <![CDATA[
public class Foo {
    Logger log = Logger.getLogger(Foo.class.getName());
    // It is very rare to see two loggers on a class, normally
    // log information is multiplexed by levels
    Logger log2= Logger.getLogger(Foo.class.getName());
}
]]>
     </example>
     </rule>

     <rule name="LoggerIsNotStaticFinal"
   		language="java"
     		since="2.0"
         message="The Logger variable declaration does not contain the static and final modifiers"
         class="net.sourceforge.pmd.lang.rule.XPathRule"
          externalInfoUrl="http://pmd.sourceforge.net/rules/java/logging-java.html#LoggerIsNotStaticFinal">
     <description>
In most cases, the Logger reference can be declared as static and final.
     </description>
     <priority>2</priority>
     <properties>
         <property name="xpath">
             <value>
                 <![CDATA[
//VariableDeclarator
 [parent::FieldDeclaration]
 [../Type/ReferenceType
  /ClassOrInterfaceType[@Image='Logger']
   and
  (..[@Final='false'] or ..[@Static = 'false'] ) ]
                ]]>
             </value>
         </property>
     </properties>
     <example>
 <![CDATA[
public class Foo{
    Logger log = Logger.getLogger(Foo.class.getName());					// not recommended

    static final Logger log = Logger.getLogger(Foo.class.getName());	// preferred approach
}
]]>
     </example>
     </rule>
    
<!-- This rule will probably be implemented in a java class, since we need to search the logger name 
first -->
<!--
     <rule name="LogBlockWithoutIf"
         message="There is log block not surrounded by if"
         class="net.sourceforge.pmd.lang.rule.XPathRule">
     <description>
When many log statements are used, it is convenient to surround them with an if statement.
     </description>
     <properties>
         <property name="xpath">
             <value>
                 <![CDATA[
                ]]>
             </value>
         </property>
     </properties>
        <priority>2</priority>

     <example>
 <![CDATA[

 	// Add this for performance
	// if (log.isLoggable(Level.FINE)) { ...
 	log.fine("This happens");
	log.fine("Value of x:"+x);
	log.fine("Value of y:"+y);
	log.fine("Value of z:"+z);
	log.fine("Value of w:"+w);
 
]]>
     </example>
     </rule>
    -->


    <rule name="SystemPrintln"
   		language="java"
    		since="2.1"
         message="System.out.print is used"
         class="net.sourceforge.pmd.lang.rule.XPathRule"
          externalInfoUrl="http://pmd.sourceforge.net/rules/java/logging-java.html#SystemPrintln">
     <description>
References to System.(out|err).print are usually intended for debugging purposes and can remain in
the codebase even in production code. By using a logger one can enable/disable this behaviour at
will (and by priority) and avoid clogging the Standard out log.
     </description>
     <priority>2</priority>
     <properties>
         <property name="xpath">
             <value>
                 <![CDATA[
//Name[
    starts-with(@Image, 'System.out.print')
    or
    starts-with(@Image, 'System.err.print')
    ]
                ]]>
             </value>
         </property>
     </properties>
     <example>
 <![CDATA[
class Foo{
    Logger log = Logger.getLogger(Foo.class.getName());
    public void testA () {
        System.out.println("Entering test");
        // Better use this
        log.fine("Entering test");
    }
}
]]>
     </example>
     </rule>

    <rule  name="AvoidPrintStackTrace"
   		language="java"
    		  since="3.2"
           message="Avoid printStackTrace(); use a logger call instead."
           class="net.sourceforge.pmd.lang.rule.XPathRule"
		   externalInfoUrl="http://pmd.sourceforge.net/rules/java/logging-java.html#AvoidPrintStackTrace">
           <description>
Avoid printStackTrace(); use a logger call instead.
           </description>
           <priority>3</priority>
           <properties>
             <property name="xpath">
             <value>
<![CDATA[
//PrimaryExpression
 [PrimaryPrefix/Name[contains(@Image,'printStackTrace')]]
 [PrimarySuffix[not(boolean(Arguments/ArgumentList/Expression))]]
]]>
             </value>
             </property>
           </properties>
           <example>
<![CDATA[
class Foo {
  void bar() {
    try {
     // do something
    } catch (Exception e) {
     e.printStackTrace();
     }
   }
}
]]>
           </example>
    </rule>
    
</ruleset>

=== pmd/pmd/pmd/src/main/resources/rulesets/internal/pmdspecific.xml
<?xml version="1.0"?>

<ruleset name="PMD specific rules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
  <description>These rules check for problems that are specific to the PMD codebase and may not be applicable to other projects.</description>

  <rule name="UseInstanceOftoCompareClasses"
      language="java" since="5.0"
      message="replace o.getClass().equals(MyClass.class) with o instanceof MyClass"
      class="net.sourceforge.pmd.lang.rule.XPathRule">
    <description>replace o.getClass().equals(MyClass.class) with o instanceof MyClass. Make sure MyClass doesn't have descendants</description>
    <priority>3</priority>
    <properties>
      <property name="xpath">
        <value>
<![CDATA[
//PrimaryExpression[
(PrimaryPrefix[Name[ends-with(@Image, 'getClass')]] or PrimarySuffix[@Image='getClass'])
and
PrimarySuffix[Arguments[count(ArgumentList)=0]]
and
PrimarySuffix[@Image='equals']
and
PrimarySuffix/Arguments/ArgumentList/Expression/PrimaryExpression/PrimaryPrefix
/ResultType/Type/ReferenceType/ClassOrInterfaceType
]
]]>
        </value>
      </property>
    </properties>
  </rule>

  <rule name="ReversedUseInstanceOftoCompareClasses"
      language="java" since="5.0"
      message="replace MyClass.class.equals(o.getClass()) with o instanceof MyClass"
      class="net.sourceforge.pmd.lang.rule.XPathRule">
    <description>replace MyClass.class.equals(o.getClass()) with o instanceof MyClass. Make sure MyClass doesn't have descendants</description>
    <priority>3</priority>
    <properties>
      <property name="xpath">
        <value>
<![CDATA[
//PrimaryExpression[
PrimaryPrefix[ResultType/Type/ReferenceType/ClassOrInterfaceType]
and
PrimarySuffix[@Image='equals']
and
PrimarySuffix/Arguments/ArgumentList/Expression/PrimaryExpression[
  PrimaryPrefix[Name[ends-with(@Image, 'getClass')]]
  and
  PrimarySuffix[Arguments[count(ArgumentList)=0]]
  ]
]
]]>
        </value>
      </property>
    </properties>
  </rule>

</ruleset>

=== pmd/pmd/pmd-java/src/main/resources/ruledefs/java/android.xml
<?xml version="1.0"?>

<ruleset name="Android"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
  <description>
These rules deal with the Android SDK, mostly related to best practices.
To get better results, make sure that the auxclasspath is defined for type resolution to work.
  </description>

  <rule name="CallSuperFirst"
      since="4.2.5"
      language="java"
      message="super should be called at the start of the method"
      class="net.sourceforge.pmd.lang.rule.XPathRule"
      externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_android.html#callsuperfirst">
    <description>Super should be called at the start of the method</description>
    <priority>3</priority>
    <properties>
      <property name="xpath">
        <value><![CDATA[
//MethodDeclaration[MethodDeclarator[
  @Image='onCreate' or
  @Image='onConfigurationChanged' or
  @Image='onPostCreate' or
  @Image='onPostResume' or
  @Image='onRestart' or
  @Image='onRestoreInstanceState' or
  @Image='onResume' or
  @Image='onStart'
  ]]
    /Block[not(
      (BlockStatement[1]/Statement/StatementExpression/PrimaryExpression[./PrimaryPrefix[@SuperModifier='true']]/PrimarySuffix[@Image= ancestor::MethodDeclaration/MethodDeclarator/@Image]))]
[ancestor::ClassOrInterfaceDeclaration[ExtendsList/ClassOrInterfaceType[
  typeof(@Image, 'android.app.Activity', 'Activity') or
  typeof(@Image, 'android.app.Application', 'Application') or
  typeof(@Image, 'android.app.Service', 'Service')
]]]
]]>
        </value>
      </property>
    </properties>
    <example><![CDATA[
public class DummyActivity extends Activity {
    public void onCreate(Bundle bundle) {
        // missing call to super.onCreate(bundle)
        foo();
    }
}
]]>
    </example>
  </rule>

  <rule name="CallSuperLast"
      since="4.2.5"
      language="java"
      message="super should be called at the end of the method"
      class="net.sourceforge.pmd.lang.rule.XPathRule"
      externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_android.html#callsuperlast">
    <description>Super should be called at the end of the method</description>
    <priority>3</priority>
    <properties>
      <property name="xpath">
        <value>
          <![CDATA[
//MethodDeclaration[MethodDeclarator[
  @Image='finish' or
  @Image='onDestroy' or
  @Image='onPause' or
  @Image='onSaveInstanceState' or
  @Image='onStop' or
  @Image='onTerminate'
  ]]
   /Block/BlockStatement[last()]
    [not(Statement/StatementExpression/PrimaryExpression[./PrimaryPrefix[@SuperModifier='true']]/PrimarySuffix[@Image= ancestor::MethodDeclaration/MethodDeclarator/@Image])]
[ancestor::ClassOrInterfaceDeclaration[ExtendsList/ClassOrInterfaceType[
  typeof(@Image, 'android.app.Activity', 'Activity') or
  typeof(@Image, 'android.app.Application', 'Application') or
  typeof(@Image, 'android.app.Service', 'Service')
]]]
]]>
        </value>
      </property>
    </properties>
    <example>
      <![CDATA[
public class DummyActivity extends Activity {
    public void onPause() {
        foo();
        // missing call to super.onPause()
    }
}
]]>
    </example>
  </rule>

  <rule name="DoNotHardCodeSDCard"
      since="4.2.6"
      language="java"
      message="Do not hardcode /sdcard."
      class="net.sourceforge.pmd.lang.rule.XPathRule"
      externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_android.html#donothardcodesdcard">
    <description>Use Environment.getExternalStorageDirectory() instead of "/sdcard"</description>
    <priority>3</priority>
    <properties>
      <property name="xpath">
        <value>//Literal[starts-with(@Image,'"/sdcard')]</value>
      </property>
    </properties>
    <example>
      <![CDATA[
public class MyActivity extends Activity {
    protected void foo() {
        String storageLocation = "/sdcard/mypackage";   // hard-coded, poor approach

       storageLocation = Environment.getExternalStorageDirectory() + "/mypackage"; // preferred approach
    }
}
]]>
    </example>
  </rule>

</ruleset>

=== pmd/pmd/pmd-java/src/main/resources/ruledefs/java/comments.xml
<?xml version="1.0"?>

<ruleset name="Comments"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

  <description>
Rules intended to catch errors related to code comments
  </description>

   <rule name="CommentRequired"
         since="5.1"
         message="Comment is required"
         class="net.sourceforge.pmd.lang.java.rule.comments.CommentRequiredRule"
         externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_comments.html#commentrequired">
    <description>
Denotes whether comments are required (or unwanted) for specific language elements.
    </description>
    <priority>3</priority>
    <example>
<![CDATA[
/**
* 
*
* @author Jon Doe
*/
]]>
    </example>
  </rule>
  
    <rule name="CommentSize"
          since="5.0"
          message="Comment is too large"
          class="net.sourceforge.pmd.lang.java.rule.comments.CommentSizeRule"
          externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_comments.html#commentsize">
    <description>
Determines whether the dimensions of non-header comments found are within the specified limits.
    </description>
    <priority>3</priority>
    <example>
<![CDATA[
/**
*
*   too many lines!
*
*
*
*
*
*
*
*
*
*
*
*
*/
]]>
    </example>
  </rule>

  <rule name="CommentContent"
        since="5.0"
        message="Invalid words or phrases found"
        class="net.sourceforge.pmd.lang.java.rule.comments.CommentContentRule"
        externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_comments.html#commentcontent">
     <description>
A rule for the politically correct... we don't want to offend anyone.
  </description>
  <priority>3</priority>
  <example>
      <![CDATA[
//OMG, this is horrible, Bob is an idiot !!!
      ]]>
  </example>
   </rule>

  <rule name="CommentDefaultAccessModifier"
        since="5.4.0"
        class="net.sourceforge.pmd.lang.java.rule.comments.CommentDefaultAccessModifierRule"
        message="Missing commented default access modifier"
        externalInfoUrl="${pmd.website.baseurl}/pmd_rules_java_comments.html#commentdefaultaccessmodifier">
    <description>
        To avoid mistakes if we want that a Method, Constructor, Field or Nested class have a default access modifier
        we must add a comment at the beginning of it's declaration.
        By default the comment must be /* default */, if you want another, you have to provide a regexp.
    </description>
    <priority>3</priority>
    <properties>
        <property name="regex">
            <value>
                <![CDATA[
\/\*\s+default\s+\*\/
                ]]>
            </value>
        </property>
    </properties>
    <example>
        <![CDATA[
        public class Foo {
            final String stringValue = "some string";
            String getString() {
               return stringValue;
            }

            class NestedFoo {
            }
        }

        // should be
        public class Foo {
            /* default */ final String stringValue = "some string";
            /* default */ String getString() {
               return stringValue;
            }

            /* default */ class NestedFoo {
            }
        }
        ]]>
    </example>
  </rule>

 </ruleset>

=== pmd/pmd/pmd/src/main/resources/rulesets/releases/510.xml
<?xml version="1.0"?>

<ruleset name="510"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
  <description>
This ruleset contains links to rules that are new in PMD v5.1.0
  </description>

    <rule ref="rulesets/java/logging-jakarta-commons.xml/GuardLogStatement"/>
    <rule ref="rulesets/java/logging-java.xml/GuardLogStatementJavaUtil"/>
    <rule ref="rulesets/java/comments.xml/CommentRequired"/>
    <rule ref="rulesets/java/design.xml/AvoidProtectedMethodInFinalClassNotExtending"/>
    <rule ref="rulesets/java/design.xml/PositionLiteralsFirstInCaseInsensitiveComparisons"/>
    <rule ref="rulesets/java/strings.xml/ConsecutiveAppendsShouldReuse"/>
</ruleset>

=== pmd/pmd/pmd-core/src/test/resources/ruledefs/dummy/ruledef1.xml
<?xml version="1.0"?>
<ruleset name="Test Ruleset"
         xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

    <description>
        Ruleset used by test RuleSetReferenceIdTest
    </description>

    <rule name="RDef1Rule1"
          language="dummy"
          since="1.0"
          message="Test Rule 1"
          class="net.sourceforge.pmd.lang.rule.MockRule"
          externalInfoUrl="${pmd.website.baseurl}/rules/dummy/basic.xml#DummyBasicMockRule">
        <description>
            Just for test
        </description>
        <priority>3</priority>
        <example>
            <![CDATA[
 ]]>
        </example>
    </rule>


    <rule name="RDef1Rule2"
          language="dummy"
          since="1.1"
          message="Test Rule 2"
          class="net.sourceforge.pmd.lang.rule.XPathRule"
          externalInfoUrl="${pmd.website.baseurl}/rules/dummy/basic.xml#SampleXPathRule">
        <description>Test</description>
        <priority>3</priority>
        <properties>
            <property name="xpath">
                <value><![CDATA[
//DummyNode
                ]]></value>
            </property>
        </properties>
        <example>foo</example>
    </rule>
</ruleset>

=== pmd/pmd/pmd/src/main/resources/rulesets/java/comments.xml
<?xml version="1.0"?>

<ruleset name="Comments"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd"
    xsi:noNamespaceSchemaLocation="http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

  <description>
Rules intended to catch errors related to code comments
  </description>

   <rule name="CommentRequired"
    		  since="5.0"
        message="Comment is required"
        class="net.sourceforge.pmd.lang.java.rule.comments.CommentRequiredRule"
          externalInfoUrl="http://pmd.sourceforge.net/rules/java/comments.html#CommentRequired">
    <description>
Denotes whether comments are required (or unwanted) for specific language elements.
    </description>
    <priority>3</priority>
    <example>
<![CDATA[
/**
* 
*
* @author George Bush
*/
]]>
    </example>
  </rule>
  
    <rule name="CommentSize"
    		  since="5.0"
        message="Comment is too large"
        class="net.sourceforge.pmd.lang.java.rule.comments.CommentSizeRule"
          externalInfoUrl="http://pmd.sourceforge.net/rules/java/comments.html#CommentSize">
    <description>
Determines whether the dimensions of non-header comments found are within the specified limits.
    </description>
    <priority>3</priority>
    <example>
<![CDATA[
/**
*
*	too many lines!
*
*
*
*
*
*
*
*
*
*
*
*
*/
]]>
    </example>
  </rule>

  <rule name="CommentContent"
    		  since="5.0"
     message="Invalid words or phrases found."
     class="net.sourceforge.pmd.lang.java.rule.comments.CommentContentRule"
          externalInfoUrl="http://pmd.sourceforge.net/rules/java/comments.html#CommentContent">
     <description>
A rule for the politically correct... we don't want to offend anyone.
  </description>
  <priority>3</priority>
  <example>
      <![CDATA[
//	OMG, this is horrible, Bob is an idiot !!!
      ]]>
  </example>
   </rule>


 </ruleset>

=== pmd/pmd/pmd-java/src/main/resources/rulesets/java/controversial.xml
<?xml version="1.0"?>

<ruleset name="Controversial"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

  <description>
The Controversial ruleset contains rules that, for whatever reason, are considered controversial.
They are held here to allow people to include them as they see fit within their custom rulesets.
  </description>

    <!-- Rules, that have been moved into a category -->
    <rule ref="category/java/errorprone.xml/AssignmentInOperand" deprecated="true" />
    <rule ref="category/java/errorprone.xml/AvoidAccessibilityAlteration" deprecated="true" />
    <rule ref="category/java/errorprone.xml/AvoidLiteralsInIfCondition" deprecated="true" />
    <!-- Removed in PMD 7. -->
    <!--    <rule ref="category/java/errorprone.xml/DataflowAnomalyAnalysis" deprecated="true" />-->
    <rule ref="category/java/errorprone.xml/DoNotCallGarbageCollectionExplicitly" deprecated="true" />
    <rule ref="category/java/errorprone.xml/DontImportSun" deprecated="true" />
    <rule ref="category/java/errorprone.xml/NullAssignment" deprecated="true" />
    <rule ref="category/java/errorprone.xml/SuspiciousOctalEscape" deprecated="true" />

    <rule ref="category/java/codestyle.xml/AtLeastOneConstructor" deprecated="true" />
    <rule ref="category/java/codestyle.xml/AvoidUsingNativeCode" deprecated="true" />
    <rule ref="category/java/codestyle.xml/CallSuperInConstructor" deprecated="true" />
<!--    <rule ref="category/java/codestyle.xml/DefaultPackage" deprecated="true" />-->
    <rule ref="category/java/codestyle.xml/OnlyOneReturn" deprecated="true" />
    <rule ref="category/java/codestyle.xml/UnnecessaryConstructor" deprecated="true" />

    <rule ref="category/java/multithreading.xml/AvoidUsingVolatile" deprecated="true" />
    <rule ref="category/java/multithreading.xml/UseConcurrentHashMap" deprecated="true" />

    <rule ref="category/java/bestpractices.xml/OneDeclarationPerLine" deprecated="true" />

<!--    <rule ref="category/java/performance.xml/AvoidUsingShortType" deprecated="true" />-->

    <rule ref="category/java/design.xml/UseObjectForClearerAPI" deprecated="true" />

    <!-- The rule UnnecessaryParentheses has been merged into unnecessary.xml/UselessParentheses,
         which now lives in codestyle -->
    <rule name="UnnecessaryParentheses" deprecated="true" ref="category/java/codestyle.xml/UselessParentheses" />

</ruleset>
